version: '2.2'
networks:
  JenkinsWorkspace:
    driver: bridge
services:
  JenkinsWorkspace:
    cpus: 2
    user: root
    mem_limit: 768M
    image: jenkinsci/blueocean
    container_name: JenkinsWorkspace
    networks:
      - JenkinsWorkspace
    volumes: 
      - ./data/.ssh:/root/.ssh
      - ./data/src:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8088:8080
      - 50000:50000